package com.example.mode_xiaowangzi.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mode_xiaowangzi.bean.LoveBean;

import com.example.mode_xiaowangzi.dao.LoveBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loveBeanDaoConfig;

    private final LoveBeanDao loveBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loveBeanDaoConfig = daoConfigMap.get(LoveBeanDao.class).clone();
        loveBeanDaoConfig.initIdentityScope(type);

        loveBeanDao = new LoveBeanDao(loveBeanDaoConfig, this);

        registerDao(LoveBean.class, loveBeanDao);
    }
    
    public void clear() {
        loveBeanDaoConfig.clearIdentityScope();
    }

    public LoveBeanDao getLoveBeanDao() {
        return loveBeanDao;
    }

}
