package com.example.mode_xiaowangzi.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.mode_xiaowangzi.bean.LoveBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOVE_BEAN".
*/
public class LoveBeanDao extends AbstractDao<LoveBean, Long> {

    public static final String TABLENAME = "LOVE_BEAN";

    /**
     * Properties of entity LoveBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Longid = new Property(0, Long.class, "longid", true, "_id");
        public final static Property PublishedAt = new Property(1, String.class, "publishedAt", false, "PUBLISHED_AT");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
    }


    public LoveBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LoveBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOVE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: longid
                "\"PUBLISHED_AT\" TEXT," + // 1: publishedAt
                "\"URL\" TEXT);"); // 2: url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOVE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LoveBean entity) {
        stmt.clearBindings();
 
        Long longid = entity.getLongid();
        if (longid != null) {
            stmt.bindLong(1, longid);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(2, publishedAt);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LoveBean entity) {
        stmt.clearBindings();
 
        Long longid = entity.getLongid();
        if (longid != null) {
            stmt.bindLong(1, longid);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(2, publishedAt);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LoveBean readEntity(Cursor cursor, int offset) {
        LoveBean entity = new LoveBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // longid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // publishedAt
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LoveBean entity, int offset) {
        entity.setLongid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPublishedAt(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LoveBean entity, long rowId) {
        entity.setLongid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LoveBean entity) {
        if(entity != null) {
            return entity.getLongid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LoveBean entity) {
        return entity.getLongid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
